### ISSUE TITLE
Extract bUnit testing support to separate NuGet package

### ISSUE THREAD

**Issue by hakenr** [Blazored/LocalStorage#154] opened 2021-07-02 13:51 UTC
Blazored.LocalStorage package contains support for bUnit testing and is dependant on bUnit.Core.

...which makes it slip all the way to production environment - the bUnit.Core.dll is part of production deployment of all applications which are using Blazored.LocalStorage.

...and the bUnit.Core.dll is being downloaded to the browser (althought is is only 44B after trimming):
![image](https://user-images.githubusercontent.com/12828888/124284978-c7717b80-db4d-11eb-8aad-e659e698df81.png)

**Comment by chrissainty** [comment] 2021-07-03 09:29
Closing as duplicate of #149

**Closed by chrissainty** 2021-07-03 09:29 UTC
Labels: Feature Request, Triage
