### ISSUE TITLE
Cyrillic Character Encoding Issues

### ISSUE THREAD

**Issue by roduman** [Blazored/LocalStorage#32] opened 2019-08-19 11:01 UTC
Cyrillic Character Encoding Issues - "\u0420\u0443\u0441\u0441\u043A\u0438\u0439"

**Comment by chrissainty** [comment] 2019-08-19 14:27
Hi, could you provide a little more info on what the problem is? What you've provided isn't much to go on. Thanks.

**Comment by chrissainty** [comment] 2019-10-04 22:53
As there is no further info I'm going to close this issue. Feel free to reopen if you can provide more information.

**Closed by chrissainty** 2019-10-04 22:53 UTC
Labels: question

**Comment by CzarSibelius** [comment] 2021-04-11 04:33
Found this page when googling why my data's scandic letters (ä,ö,å) were encoded, OP probably had the same issue with cyrillic characters.

For others having the same issue, you can configure Blazored's JavaScriptEncoder in your Program.cs.

For example:

`builder.Services.AddBlazoredLocalStorage(config => config.JsonSerializerOptions.Encoder = JavaScriptEncoder.Create(UnicodeRanges.All));`

**Comment by unkovalenko** [comment] 2024-12-27 08:38
thank you. Cyrillic works correctly
