### ISSUE TITLE
[Bug] Dependency Injection is not correctly setup by extensions AddBlazoredLocalStorage

### ISSUE THREAD

**Issue by svenskmand** [Blazored/LocalStorage#105] opened 2020-08-20 13:50 UTC
**Describe the bug**
The dependency injection is not correctly set up by the `AddBlazoredLocalStorage` extension methods.

**To Reproduce**
The following program injects a null version of the `LocalStorageService storage` variable into the constructor for `StateService`:
```cs
    public class Program {
        public static async Task Main(string[] args) {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddTransient(sp => new HttpClient {
                BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
            });
            
            builder.Services.AddBlazoredLocalStorage();
            builder.Services.AddSingleton<StateService>(sp => {
                var storage = sp.GetService<LocalStorageService>();
                return new StateService(storage);
            });

            await builder.Build().RunAsync();
        }
    }
```

**Expected behavior**
The `LocalStorageService storage` should not be null but instead be an instance of the `LocalStorageService ` type.

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Hosted Blazor WebAssembly

I have not tried this on the other hosting models.

**Additional context**
The program can be made to work if it is changed to not use the `AddBlazoredLocalStorage` extension methods but instead create the `LocalStorageService` instance it self like this:
```cs
    public class Program {
        public static async Task Main(string[] args) {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddTransient(sp => new HttpClient {
                BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
            });

            builder.Services.AddSingleton<LocalStorageService>(sp => {
                var runtime = sp.GetService<IJSRuntime>();
                var options = sp.GetService<IOptions<LocalStorageOptions>>();
                return new LocalStorageService(runtime, options);
            });
            builder.Services.AddSingleton<StateService>(sp => {
                var storage = sp.GetService<LocalStorageService>();
                return new StateService(storage);
            });

            await builder.Build().RunAsync();
        }
    }
```

**Comment by chrissainty** [comment] 2020-08-20 14:18
This is a common mistake, you're trying to inject a scoped service into a singleton. This is not allowed by ASP.NET Core's service container. If you change your `StateService` to have a scoped lifetime then everything will work as expect.

**Comment by svenskmand** [comment] 2020-08-20 15:37
Ok, but I would like to have the service as a Singleton, why should that not bee supported?

**Comment by chrissainty** [comment] 2020-08-20 15:43
Firstly, singleton and scoped are the same in Blazor WebAssembly. I wrote a [blog post coving this](https://chrissainty.com/service-lifetimes-in-blazor/) in some detail a couple of years ago, it might be worth a read.

Outside of Blazor the specific reason you can't inject a scoped service into a singleton is that it would break the lifetime expectation of the scoped service. In a ASP.NET Core WebAPI app a scoped service is tied to the lifetime of the request, where as a singleton is tied to the lifetime of the application. If you were allowed to inject the scoped service into the singleton, it would no longer be scoped as it would persist for the lifetime of the singleton instance it was being injected into.

I hope that makes sense. As this isn't a bug I'm going to close the issue but I'm happy to answer any more questions you have on the subject.

**Closed by chrissainty** 2020-08-20 15:43 UTC
Labels: Bug, Triage

**Comment by svenskmand** [comment] 2020-08-20 15:57
I am trying to use Web Object Storage to persist user input between closing tabs and closing the browser and then asynchronous store that data in a backed service. Because of that I would like to have a Singleton service that saves the state and stores it in the back end when it is online.

So my question is, since you have made it difficult to use your `LocalStorageService` as a Singleton, is that because it leaks memory or is implented in a way that would make it not work as a Singleton service? Or what is the reason for not making it easy to use and a Singleton? 🙂

**Comment by chrissainty** [comment] 2020-08-20 16:46
Did you read the blog post? I would suggest you spend some time learning a bit more about how Blazor WebAssembly behaves in n regards to dependency injection. As I said in my previous comment, singleton and scoped behave exactly the same in Blazor Wasm. 

I'm not sure if you're being deliberately condescending with your comment on this library being difficult to use. Again if you understood more about how DI worked with Blazor and it's different hosting models you would understand that libraries such as this one which cater for both hosting model will use scoped as it behaves the same way in both hosting models and will work for everyone. Again, one more time, scoped and singleton behave the same way in Blazor wasm.

**Comment by svenskmand** [comment] 2020-08-20 18:16
I am not trying to be condescending. I am just trying to figure out why you do not want the service to be used as a singleton. I asked about your implementation because you might have chosen to only used the scoped lifetime because of the way you have implemented it, see [this post](https://medium.com/volosoft/asp-net-core-dependency-injection-best-practices-tips-tricks-c6e9c67f9d96) that mentions this as a reason to limit the scope of a service.

You say that the Scoped and Singleton lifetimes behaves the same in Blazor. Then I do not understand why using `AddBlazoredLocalStorage` will not also allow the service to be used as a singleton. There is no documentation stating that it can only be used as a scoped service, so it is natural to assume that it can be used as a singleton since the service is responsible for persisting state.

Just my two cents :)

**Comment by chrissainty** [comment] 2020-08-20 18:29
Your **assumption** is that Blazor behaves in the same way as ASP.NET Core applications, it doesn't. ASP.NET Core apps have a request and response model and are stateless. Blazor is stateful.

When a user navigates to a Blazor Wasm application it is downloaded and run in their browser, it's not a shared instance on a server as ASP.NET Core apps are. Hence, it's better to think of it more as a desktop application. Therefore singleton and scoped act the same way, as there is no request scoped does exactly what singleton does (something you'd have seen if you'd read the article I posted). The reason ALL blazor libraries use scoped for services is because there would be major problems when the library was consumer in a Blazor Server application. There, scoped and singleton do behave as they would in an ASP.NET Core app. So if this library used singleton all users of a Blazor Server app would be able to access the same service instance and therefore each others data.

**Comment by alix-tlse** [comment] 2022-12-07 09:01
Hello,

I have read the [blog post](https://chrissainty.com/service-lifetimes-in-blazor/), i have read the microsoft documentation : [Blazor WebAssembly apps don't currently have a concept of DI scopes. Scoped-registered services behave like Singleton services.](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-7.0#service-lifetime)... but, it's a fact you can't inject scope services in a singleton service.

I'm not agree with the assumption "ALL blazor libraries use scoped for services" :

> The following services are explicitly registered as Singleton in Blazor WASM and Hybrid and as Scoped in Blazor Server:
> 
>     IJSRuntime and the
>     NavigationManager
[Differences of registrations in different Blazor editions](https://www.thinktecture.com/en/blazor/dependency-injection-scopes-in-blazor/)

I understand it's not a bug, but can you add the possibility to inject the service as a singleton, because in WASM only app it can have sense. We can do that by adding an optional bool parameter "asSingleton" or a second method "AddBlazoredLocalStorageFormWasmApp"...

If you want (and you think it could work...), I can do a pull request with something like this :
```
        public static IServiceCollection AddBlazoredLocalStorage(this IServiceCollection services, Action<LocalStorageOptions> configure, bool asSingleton = false)
        {
            if (asSingleton)
            {
                return services.AddSingleton<IJsonSerializer, SystemTextJsonSerializer>()
                    .AddSingleton<IStorageProvider, BrowserStorageProvider>()
                    .AddSingleton<ILocalStorageService, LocalStorageService>()
                    .AddSingleton<ISyncLocalStorageService, LocalStorageService>()
                    .Configure(delegate (LocalStorageOptions configureOptions)
                    {
                        configure?.Invoke(configureOptions);
                        configureOptions.JsonSerializerOptions.Converters.Add(new TimespanJsonConverter());
                    });
            }
            else
            {
                return services.AddScoped<IJsonSerializer, SystemTextJsonSerializer>()
                    .AddScoped<IStorageProvider, BrowserStorageProvider>()
                    .AddScoped<ILocalStorageService, LocalStorageService>()
                    .AddScoped<ISyncLocalStorageService, LocalStorageService>()
                    .Configure(delegate (LocalStorageOptions configureOptions)
                    {
                        configure?.Invoke(configureOptions);
                        configureOptions.JsonSerializerOptions.Converters.Add(new TimespanJsonConverter());
                    });
            }
        }
```

**Comment by chrissainty** [comment] 2022-12-07 09:08
@alix-tlse Pitty you didn't take the time to read the readme where it explains how to register the services as Singletons..... 🤦‍♂️

https://github.com/Blazored/LocalStorage#registering-services-as-singleton---blazor-webassembly-only

**Comment by alix-tlse** [comment] 2022-12-07 09:23
Sorry I didn't saw it... My google search bring me here.

Thank you for you're quick response !
